# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hello <- function() {
    .Call(`_rcppsimdgeojson_hello`)
}

.fparse_sfc <- function(x, on_demand = FALSE) {
    .Call(`_rcppsimdgeojson_fparse_sfc`, x, on_demand)
}

.fload_sfc <- function(x) {
    .Call(`_rcppsimdgeojson_fload_sfc`, x)
}

