# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hello <- function() {
    .Call(`_rcppsimdgeojson_hello`)
}

.parse_geojson <- function(x) {
    .Call(`_rcppsimdgeojson_parse_geojson`, x)
}

.read_geojson <- function(x) {
    .Call(`_rcppsimdgeojson_read_geojson`, x)
}

