# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hello <- function() {
    .Call(`_rcppsimdgeojson_hello`)
}

#' Parse GeoJSON Strings
#'
#' @param x GeoJSON string
#'
#' @param expand_geometries default: `FALSE`
#'
#'
.fparse_sfc <- function(x, expand_geometries = FALSE) {
    .Call(`_rcppsimdgeojson_fparse_sfc`, x, expand_geometries)
}

#' Load GeoJSON Files
#'
#' @param x GeoJSON file
#'
#' @param expand_geometries default: `FALSE`
#'
#'
.fload_sfc <- function(x, expand_geometries = FALSE) {
    .Call(`_rcppsimdgeojson_fload_sfc`, x, expand_geometries)
}

